### ISSUE TITLE
俩个小问题

### ISSUE THREAD

**Issue by Aincvy** [season-studio/felisMindmap#1]
首先， 很感谢开发了这个插件， 我今天第一次使用， 感觉还不错。 

但是我目前发现两个小问题，有些影响使用。

1. 新建一个主题之后， 输入框在大约2-4秒内会失去焦点。  即使在文字得输入过程中， 也会失去焦点。
2. 无法保存， 无论是`ctrl+s` 还是 `File / Save` 都无法保存， 具体表现是 点击了之后， vscode 标签页上得圆点不消失。

**Comment by season-studio** [comment]
感谢反馈。
由于本程序是先实现了PWA版本，再迁移到vscode插件中，所以有些文件处理机制与vscode没有做好兼容，造成了问题。
所述的两个异常现象，是由三个与vscode的文件机制兼容BUG造成的。
（1）对于新建的还处于未命名状态下的思维导图，vscode中文档模型的文档路径同时关联了一个编辑过程临时备份文件，到进行File/Save菜单操作的时候，代码中误将临时备份文件路径作为了文档的正式文件路径，此为File/Save没有生效的第1个原因。
（2）通过快捷键或者插件内部的File/Save菜单触发的文件保存操作，整个过程都处于插件内部，vscode当前版本似乎没有提供对应的机制让vscode宿主程序能够收到插件自身已完成了文件保存的通知，所以文件保存后vscode没有消掉文件标签中的原点。我目前修订这个问题方式，是让快捷键或者插件内部的File/Save菜单触发的文件保存中转通过vscode的内建命令"workbench.action.files.save"来二次触发，这样vscode宿主就可以知道文件发生了保存操作。
（3）vscode在每次编辑动作事件发生后，都会触发一次临时备份文件的保存处理。比如新建一个主题节点的时候，就属于触发了一个编辑事件。我原始代码中将临时备份文件的保存处理过程归一到正常文件的保存处理过程中。在保存处理中，为了捕获思维导图的缩略图，我会先尝试停止所有正在进行的编辑过程，避免编辑元素（比如输入框）遮挡住部分主题画面。这就造成了当新建一个主题节点的后，编辑框会突然消失。目前修订该问题的方式是，将临时备份文件的保存处理做个特殊化，即保存临时备份文件时，不停止正在进行的编辑过程。
针对上述问题的修订，目前已发布了新的插件版本（1.0.1）。请尝试更新插件，看看问题是否已修复。

**Comment by Aincvy** [comment]
经过升级后确认， 这俩问题都已经修复  😄
