### ISSUE TITLE
建议：深色模式支持

### ISSUE THREAD

**Issue by Jakoers** [season-studio/felisMindmap#3]
深色主题下白色背景亮度比较高，比较费眼睛。作者能考虑一下支持深色模式或者是将背景改成深色吗？

**Comment by season-studio** [comment]
正好要发布新版本，就把深色模式一道加进去了。启用方式在菜单“插件”--“扩展主题”--“深色模式”下面。
![image](https://user-images.githubusercontent.com/66667151/220346641-ce956a0a-a633-4cb9-a075-9dad455662a1.png)
