### ISSUE TITLE
宽度和换行

### ISSUE THREAD

**Issue by taoqf** [season-studio/felisMindmap#4]
1. 在xmind中设置的宽度打开后失效
2. 无法手动添加换行，也不能设置宽度

麻烦有空看下这两个问题

**Comment by taoqf** [comment]
我可能没说清楚，我再描述一下这两个问题（实际上是一个问题）
1. 使用xmind应用程序创建一个文件，添加结点，输入很长很长的文本，设置单元格的宽度，结点的内容会自动变为多行，方便查看。然后关闭再打开这个文件后，发现宽度是保存了的。但在vscode的扩展中打开，会变成很长很长一行文字。
2. 在vscode中打开或创建一个xmind文件，添加结点，输入很长很长的文本，此时，不能设置单元格的宽度，也不能将文本换行。

请问有什么办法可以在一个结点输入长文本吗？

**Comment by season-studio** [comment]
@taoqf 
您反馈的问题我已了解。很抱歉现有的版本暂未实现对应的或可替代的功能。
原因在于我设计之初认为，长文本应该体现在备注项中，而非直接写在主题正文中。所以，当前的版本我并没有处理主题正文换行的对应逻辑。
我已关注到您的需求与我预想的差异性。我会在后续的版本更新中考虑对应功能的实现方案，但可能进展并不会太快。
感谢您的关注。

**Comment by taoqf** [comment]
多谢回复，如果可能请指点一下：我可以抽时间帮助你完成这个功能。

**Comment by taoqf** [comment]
多谢回复，如果可能请指点一下：我可以抽时间帮助你完成这个功能。

**Comment by season-studio** [comment]
@taoqf 感谢关注。
如果需要修订此功能，您需要关注我的另一个项目[mindmap.svg.js](https://github.com/season-studio/mindmap.svg.js)，felisMindmap的导图处理是以这个项目为基础实现的。该项目的topic.js中的"on-ebevent-rendering"方法负责完成每个主题的渲染工作。
这个项目的思维导图是利用SVG图来实现的，其中主题正文通过<text class="season-topic-title">元素实现。<text>元素本身不支持自动换行，所以，理论上要实现您的需求，需要将主题文本切分成多个段，通过在text元素中插入多个tspan来实现。其中主题文本切分多个段的过程，除了根据换行符进行切分外，还需要计算根据设定的主题宽度和主题字体风格下可以容纳的单行字符数量，进而为没有换行符的长文本进行切段。其中还要注意，如果主题风格设定的字体不是等宽字体，则需要动态计算单行字符数量，不能使用同一标准对待所有导图的主题节点。所以，实现此功能时，需要仔细评估计算逻辑的设定，以避免在渲染工作中消耗太多时间。这也是我之前回复"进展不会太快"的原因。
另外，根据您的需求，可能需要为主题定义一个“默认最大宽度”的配置参数，建议将此参数定义在mindmapEnv.js的DefaultConfig数据中。
期待您为此功能贡献代码。谢谢。

**Comment by season-studio** [comment]
@taoqf 我已提交了新的修改，以支持主题标题文字的换行和自定义标题文字最大显示宽度的功能。
然而，新的实现的效果与xmind中还是存在一些差异，已知的包括：
（1）因为字体的不同，当设置了同样的宽度值后，同一xmind文件在xmind程序与在felisMindmap中的换行位置并不一定是一样的；
（2）我的实现逻辑是设定主题标题行的最大宽度，当主题标题的实际长度并未达到最大宽度时，felisMindmap并不会主动“撑大”主题的整体宽度；而xmind程序的实现逻辑是设定主题的固定宽度，即便主题标题实际长度没有达到宽度值，整个主题的宽度依然会被“撑大”到设定的固定宽度。
另外，请注意，我手上没有再安装旧版的xmind（导图内容以xml格式存储的那个版本），我没有进一步分析旧版xmind是否支持主题宽度自定义、以及它自定义宽度值存储的位置，所以，目前我的实现也仅对新版xmind中的自定义宽度值做支持。
vscode插件商城中的版本已同步发布。欢迎测试验证。

**Comment by taoqf** [comment]
太棒了，辛苦了。
我根本也不期望能兼容旧版xmind,我认为确实没那个必要。
现在来说，已经基本可以满足我的使用场景了。
顺便问一下：在xmind中导图的样式`skelenton`的支持容易吗？如果容易，建议添加上，因为我们使用向右方向的逻辑图的时候还是挺多的。
再有一个建议：xmind的右键拖动移动的操作习惯还是不错的，可以借鉴一下。因为左键有时会点到主题结点上。

**Comment by season-studio** [comment]
@taoqf skelenton是什么样式？我在xmind似乎没有看到对应的功能项。麻烦截个图或者详细说明一下。

**Comment by taoqf** [comment]
![image](https://github.com/season-studio/felisMindmap/assets/15901911/868600cf-45a5-4407-b5c2-3c8aa8c9465f)
这个呀，可能中文名字我不知道怎么叫。

**Comment by season-studio** [comment]
@taoqf 还是没有明白。可能我们的xmind版本不一样，我没有看到这个界面。
![image](https://github.com/season-studio/felisMindmap/assets/66667151/0ec731c3-23e8-42a2-9a61-2a4e6105b199)
或者你描述一下它的具体功能、作用吧。

**Comment by taoqf** [comment]
你这里有的呀，你试试两个操作：
1. 你截图右侧Structure点击看看有没有其它的
2. 右上角那个图是不是也是可以点的

**Comment by taoqf** [comment]
有人不喜欢使用这种样式的图，希望可以改成中心主题在左侧，分支在右侧那种。
