### ISSUE TITLE
[功能请求] 类似 vim 的按键绑定

### ISSUE THREAD

**Issue by Mingzefei** [season-studio/felisMindmap#6]
很棒的插件！
可以考虑参考 vim 的逻辑改进一些按键绑定，进一步提升便捷性。

例如：
- 使用 `hjkl` 分别代替 左上下右 按键，实现主题移动；
- 使用 `a` 或者 `i` 开始编辑内容；
- 使用 `<esc>` 退出编辑模式，切换到主题移动模式；

上面的第1点，我推测应该容易实现，只需要将主题移动的方向键绑定暴露在 `快捷键` 选项中。
第2和3点，开始编辑和退出编辑，我已经通过修改当前版本的 `快捷键` 实现了。
可以进一步规范用法，如果作者愿意实现一个全面的 vim 模式的话。

**Comment by season-studio** [comment]
已增加移动主题焦点的快捷键指派功能。
至于vim风格的配置，我没有做（我比较少用vim，不是太熟悉它的快捷键）。
为了方便大家设置和分享不同风格的快捷键设定，我增加了偏好设置的导入和导出功能，并且建立了https://github.com/season-studio/felisMindmap.assets仓库，用来存储和分享额外的偏好设置预设文件。或许你可以作为首个贡献者，提交一份vim风格的快捷键偏好预设文件。 @Mingzefei

**Comment by Mingzefei** [comment]
非常感谢！
我已经向那个仓库提交了一次 [pull request](https://github.com/season-studio/felisMindmap.assets/pull/1)，请查阅。

**Comment by season-studio** [comment]
多谢提交preset。您的pull request 已合并 。
